site_name: Lure Fishing Study Guide
site_url: https://kaizhiyang.github.io/Lure-Fishing-Study-Guide
site_author: Kaizhi Yang
site_description: Lure Fishing Self-learning Site
repo_url: https://github.com/KaizhiYang/Lure-Fishing-Study-Guide
repo_name: Lure-Fishing-Study-Guide
copyright: Copyright &copy; 2025 - present Kaizhi Yang
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github-alt
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top

    - header.autohide

    - toc.follow

    - search.suggest
    - search.highlight
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KaizhiYang/Lure-Fishing-Study-Guide
      name: Lure Fishing Study Guide Github Page

  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

plugins:
  - glightbox
  - search

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - Home: index.md
  - Guide:
    - How to use this Guide: guide/how_to_use_the_guide.md
    - Basics:
      - Tie a Knot: guide/basics/tie_a_knot.md
      - Rod: guide/basics/rod.md
      - Reel: guide/basics/reel.md
      - Line: guide/basics/line.md
      - Hooks: guide/basics/hooks.md
      - Lure & Bait: guide/basics/lure_and_bait.md
    - Drop Shot: 
      - Beginner: guide/drop_shot/beginner.md
  - Freshwater Fish: freshwater_fish.md